apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: nfs-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500G
