apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: jellyfin
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - hard
  nfs:
    path: /mnt/ePool/kubdata
    server: 192.168.1.40
    readOnly: false
