apiVersion: v1
kind: Service
metadata:
  name: nodeport-jellyfin
  namespace: jellyfin
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-forward-port-algorithm: "leastconn"
spec:
  type: NodePort
  ports:
  - port: 8096
    name: http
    targetPort: 8096
    nodePort: 30001
  selector:
    app: jellyfin
