apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-forward-port-algorithm: "leastconn"
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30000
  selector:
    app: nginx
